version: '3.8'
services:
  web:
    container_name: dst-web
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
